### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by Bytegm**
Some of the strings was returned to their English versions due to large discrepancies in Russian or not yet implemented.

### CODE REVIEW

**Comment by Bytegm** [comment]
Translated this mod for a long time, little by little, so all the strings were mixed up compared to en_US.lang

**Comment by Lothrazar** [comment]
Lots of changes here are staying in the same language and just updating the translation? At least i assume they are corrections?

Thoughts  @kellixon  ?

**Comment by Bytegm** [comment]
@Lothrazar Yes, I corrected the translation of most of the lines to a more accurate one, since most of them distorted the Russian language.

**Comment by Bytegm** [comment]
And those lines that I returned to their English versions, due to the fact that these items are not implemented in the game.
Or due to the fact that in Russian the translation does not sound correctly

**Comment by Bytegm** [comment]
If you insist I can translate all the lines to the end.

**Comment by Lothrazar** [comment]
thanks Bytegem for the PR, sorry for not responding in a while. This is still a good PR that i like so im going to reopen for more review, if thats ok.  Gmail reminded me of this. Ive been busy in 1.14 land for a while

**Pull request merged**
